export const GALOIS_FIELD_256_SIZE = 256
export const GALOIS_FIELD_256_SHIFT = 285
export const GALOIS_FIELD_ALPHA = 2

export const BCH_FORMATTING_GENERATOR_POLYNOMIAL = 1335
export const BCH_FORMATTING_TOTAL_LENGTH = 15
export const BCH_FORMATTING_CONTENT_BITS_AMOUNT = 5

export const BCH_VERSION_GENERATOR_POLYNOMIAL = 7973
export const BCH_VERSION_TOTAL_LENGTH = 18
export const BCH_VERSION_CONTENT_BITS_AMOUNT = 6