export const CONTAINER_IS_NOT_FOUND_ERROR = new Error('Container is not found')
export const ELEMENT_IS_NOT_FOUND_ERROR = new Error('Element is not found')
export const CANVAS_CONTEXT_ERROR = new Error('Canvas content is invalid')
export const ELEMENT_TYPE_ERROR = new Error('Element type error')
export const FILE_TYPE_ERROR = new Error('File type is unsupported')
